import os
os.system('yum update')
os.system('yum -y install wget')
os.system('wget https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm')
os.system('rpm -Uvh --replacepkgs pgdg-redhat-repo-latest.noarch.rpm')
os.system('yum -y install postgresql12-server postgresql12-docs postgresql12-contrib postgresql12-plperl postgresql12-plpython postgresql12-pltcl postgresql12-test rhdb-utils gcc-objc postgresql12-devel --skip-broken')
os.system('/usr/pgsql-12/bin/postgresql-12-setup initdb')
os.system('updsystemctl start postgresql-12ate')
os.system('systemctl enable postgresql-12')
os.system('yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm')
os.system('yum install -y https://rpms.remirepo.net/enterprise/remi-release-9.rpm')
os.system('yum install -y yum-utils')
os.system('yum-config-manager --enable remi-php74')
os.system('yum -y install httpd php74-php mod_ssl php74-php-pear php74-php-bcmath php74-php-cli php74-php-ldap php74-php-pdo php74-php-pgsql php74-php-gd  php74-php-mbstring php74-php-pecl-zip')
os.system('systemctl start httpd')
os.system('systemctl enable httpd')
os.system('wget https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/e/epel-release-9-7.el9.noarch.rpm')
os.system('wget http://rpms.remirepo.net/enterprise/remi-release-9.rpm')
os.system('yum -y update')
os.system('yum -y install php74-php-mcrypt*')

archi=open("/var/lib/pgsql/12/data/pg_hba.conf",'w')
archi.write("# TYPE  DATABASE        USER            ADDRESS                 METHOD\n\n")
archi.write("# 'local' is for Unix domain socket connections only\n")
archi.write("local   all                postgres,dbkerp_conexion                  trust\n")
archi.write("local   all             all                                     md5\n")
archi.write("# IPv4 local connections:\n")
archi.write("host    all             all             127.0.0.1/32            md5\n")
archi.write("host    all             all             192.168.0.0/16          md5\n")
archi.write("# IPv6 local connections:\n")
archi.write("host    all             all             ::1/128                 md5\n")
archi.close()

f = open("/var/lib/pgsql/12/data/postgresql.conf",'r')
chain = f.read()
chain = chain.replace("pg_catalog.english","pg_catalog.spanish")
chain = chain.replace("log_destination = 'stderr'","log_destination = 'csvlog'")
chain = chain.replace("log_filename = 'postgresql-%a.log'","log_filename = 'postgresql-%Y-%m-%d.log'")
chain = chain.replace("log_truncate_on_rotation = on","log_truncate_on_rotation = off")
chain = chain.replace("#log_error_verbosity = default","log_error_verbosity = verbose")
chain = chain.replace("#log_statement = 'none'","log_statement = 'mod'")
chain = chain.replace("iso, mdy","iso, dmy")
f.close()

otro = open("/var/lib/pgsql/12/data/postgresql.conf",'w')
otro.write(chain)
otro.close()
s = open("/var/lib/pgsql/12/data/postgresql.conf",'a')
s.write("listen_addresses = '*'\n")
s.write("bytea_output = 'escape'\n")
s.close()

os.system('sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD \'postgres\';"')
os.system('sudo -u postgres psql -c "CREATE DATABASE dbkerp WITH ENCODING=\'UTF8\';"')
os.system('sudo -u postgres psql -c "CREATE USER dbkerp_conexion WITH PASSWORD \'dbkerp_conexion\';"')
os.system('sudo -u postgres psql -c "ALTER ROLE dbkerp_conexion SUPERUSER;"')
os.system('sudo -u postgres psql -c "CREATE USER dbkerp_admin WITH PASSWORD \'a1a69c4e834c5aa6cce8c6eceee84295\';"')
os.system('sudo -u postgres psql -c "ALTER ROLE dbkerp_admin SUPERUSER;"')

os.system('systemctl restart postgresql-12')
os.system('sudo yum -y install git-core')
os.system('mkdir /var/www/html/kerp')
os.system('mkdir /var/www/html/kerp/pxp')
os.system('mkdir /var/www/html/kerp/sis_presupuestos')
os.system('mkdir /var/www/html/kerp/sis_contabilidad')
os.system('mkdir /var/www/html/kerp/sis_adquisiciones')
os.system('mkdir /var/www/html/kerp/sis_tesoreria')
os.system('mkdir /var/www/html/kerp/sis_sigep')
os.system('mkdir /var/www/html/kerp/sis_contratos')
os.system('mkdir /var/www/html/kerp/sis_reclamo')
os.system('mkdir /var/www/html/kerp/sis_almacenes')
os.system('mkdir /var/www/html/kerp/sis_planillas')
os.system('mkdir /var/www/html/kerp/sis_costos')
os.system('mkdir /var/www/html/kerp/sis_kactivos_fijos')
os.system('git clone https://github.com/ofepbolivia/pxp.git /var/www/html/kerp/pxp')
os.system('chown -R apache.apache /var/www/html/kerp/')
os.system('chmod 700 -R /var/www/html/kerp/')
os.system('git clone https://github.com/ofepbolivia/sis_presupuestos.git /var/www/html/kerp/sis_presupuestos')
os.system('git clone https://github.com/ofepbolivia/sis_contabilidad.git /var/www/html/kerp/sis_contabilidad')
os.system('git clone https://github.com/ofepbolivia/sis_adquisiciones.git /var/www/html/kerp/sis_adquisiciones')
os.system('git clone https://github.com/ofepbolivia/sis_tesoreria.git /var/www/html/kerp/sis_tesoreria')
os.system('git clone https://github.com/ofepbolivia/sis_sigep.git /var/www/html/kerp/sis_sigep')
os.system('git clone https://github.com/ofepbolivia/sis_contratos.git /var/www/html/kerp/sis_contratos')
os.system('git clone https://github.com/ofepbolivia/sis_reclamo.git /var/www/html/kerp/sis_reclamo')
os.system('git clone https://github.com/ofepbolivia/sis_almacenes.git /var/www/html/kerp/sis_almacenes')
os.system('git clone https://github.com/ofepbolivia/sis_planillas.git /var/www/html/kerp/sis_planillas')
os.system('git clone https://github.com/ofepbolivia/sis_costos.git /var/www/html/kerp/sis_costos')
os.system('git clone https://github.com/ofepbolivia/sis_kactivos_fijos.git /var/www/html/kerp/sis_kactivos_fijos')

f = open("/var/www/html/kerp/pxp/lib/DatosGenerales.sample.php")
g = open("/var/www/html/kerp/pxp/lib/DatosGenerales.php","w")
linea = f.readline()
while linea != "":
        g.write(linea)
        linea = f.readline()

g.close()
f.close()

f = open("/var/www/html/kerp/pxp/lib/DatosGenerales.php",'r')
chain = f.read()
chain = chain.replace("/web/lib/lib_control/","/kerp/pxp/lib/lib_control/")
chain = chain.replace("/kerp-boa/","/kerp/")
chain = chain.replace("/var/lib/pgsql/9.1/data/pg_log/","/var/lib/pgsql/12/data/pg_log/")
f.close()
otro = open("/var/www/html/kerp/pxp/lib/DatosGenerales.php",'w')
otro.write(chain)
otro.close()

os.system("ln -s /var/www/html/kerp/pxp/lib /var/www/html/kerp/lib")
os.system("ln -s /var/www/html/kerp/pxp/index.php /var/www/html/kerp/index.php")
os.system("ln -s /var/www/html/kerp/pxp/sis_generador /var/www/html/kerp/sis_generador")
os.system("ln -s /var/www/html/kerp/pxp/sis_organigrama /var/www/html/kerp/sis_organigrama")
os.system("ln -s /var/www/html/kerp/pxp/sis_parametros /var/www/html/kerp/sis_parametros")
os.system("ln -s /var/www/html/kerp/pxp/sis_seguridad /var/www/html/kerp/sis_seguridad")
os.system("ln -s /var/www/html/kerp/pxp/sis_workflow /var/www/html/kerp/sis_workflow")

os.system("mkdir /var/www/html/kerp/reportes_generados")
os.system("setfacl -R -m u:apache:wrx /var/www/html/kerp/reportes_generados")
os.system("setfacl -R -m u:postgres:wrx /var/www/html")
os.system("chcon -Rv --type=httpd_sys_rw_content_t /var/www/html/kerp/")
os.system("setsebool -P httpd_can_network_connect_db=1")
os.system("setsebool -P httpd_can_network_connect 1")

os.system("firewall-cmd --permanent --add-port=22/tcp")
os.system("firewall-cmd --permanent --add-port=80/tcp")
os.system("firewall-cmd --permanent --add-port=5432/tcp")
os.system("firewall-cmd --permanent --add-port=8010/tcp")
os.system("firewall-cmd --reload")

os.system("php /var/www/html/kerp/lib/ratchet/pxp-Server.php > /dev/null 2>&1 &")
os.system("setfacl -R -m u:postgres:wrx /root")

os.system('pg_restore -U postgres -d dbkerp -x -O --disable-triggers -v dbkerp_v2024')
